/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hasckercapitalist;

import javax.swing.JOptionPane;

/**
 *
 * @author 55119
 */
public class JInternalHabilidades extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalHabilidades
     */
    public JInternalHabilidades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAtkWirelles = new javax.swing.JButton();
        btnInvadirDB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnPhishing = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Habilidades"));

        btnAtkWirelles.setText("Ataque Wirelles");
        btnAtkWirelles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtkWirellesActionPerformed(evt);
            }
        });

        btnInvadirDB.setText("Invadir DB");
        btnInvadirDB.setEnabled(false);
        btnInvadirDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvadirDBActionPerformed(evt);
            }
        });

        jLabel1.setText("Custo 30,00");

        jLabel2.setText("Custo 150,00");

        jLabel3.setText("<html>Descrição: Se especializar em atacar redes wireless e ter uma noção de<br> como a rede funciona. <html>");

        jLabel4.setText("<html>Ações liberadas: Descobrir senha de WiFi, Derrubar Wifi, Escanear rede <html>");

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html>A habilidade só desbloqueia quando você ativa a habilidade \"Ataque Wirelles\"</html>");
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), null));

        jLabel6.setText("<html>Descrição:Saber procurar o DB de um\nsite e achar a senha do\nadm. <html>");

        jLabel7.setText("<html>Ações liberadas: Invadir DB, Entrar como\nadm<html>");

        btnPhishing.setText("Pishing");
        btnPhishing.setEnabled(false);
        btnPhishing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhishingActionPerformed(evt);
            }
        });

        jLabel8.setText("Custo 2000,00");

        jLabel9.setBackground(new java.awt.Color(204, 255, 204));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("<html>A habilidade só desbloqueia quando você ativa a habilidade \"Invadir DB\"</html>");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 255, 255), null));

        jLabel10.setText("<html>Descrição:Vamos aprender a dar golpes e roubar senhas ? Com essa habilidade você vai conseguir enganar as pessoas e conseguir suas credenciais. <html>");

        jLabel11.setText("<html>Ações liberadas: Spear phishing,  Clone phishing, 419/scams nigerianos, Phone phishing<html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInvadirDB, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPhishing, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAtkWirelles)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtkWirelles, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(btnInvadirDB, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(btnPhishing, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        setBounds(670, 0, 408, 491);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtkWirellesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtkWirellesActionPerformed
        // TODO add your handling code here:
        if (JPrincipal.Dindin >= 30){ //dinheiro para a compra
            JOptionPane.showMessageDialog(null,"Parabéns, você conseguiu novas ações!","Aviso",JOptionPane.INFORMATION_MESSAGE);
            JPrincipal.level = 1; //level para atualizar as acoes
            JPrincipal.Dindin -= 30; //tira o dinheiro usado
            btnAtkWirelles.setEnabled(false); //botao bloqueado para não comprar de novo
            btnInvadirDB.setEnabled(true); //habilita nova habilidade
            JPrincipal.reputacao += 250; //ganha reputacao no principal
        }
        else{
             JOptionPane.showMessageDialog(null,"Dinheiro insuficiente!","Aviso",JOptionPane.INFORMATION_MESSAGE); 
        }
    }//GEN-LAST:event_btnAtkWirellesActionPerformed

    private void btnInvadirDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvadirDBActionPerformed
        // TODO add your handling code here:
        if (JPrincipal.Dindin >= 150){
            JOptionPane.showMessageDialog(null,"Parabéns, você conseguiu novas ações!","Aviso",JOptionPane.INFORMATION_MESSAGE);
            JPrincipal.level = 2;
            JPrincipal.Dindin -= 150;
            btnInvadirDB.setEnabled(false);
            btnPhishing.setEnabled(true);
            JPrincipal.reputacao += 500;
        }
        else{
             JOptionPane.showMessageDialog(null,"Dinheiro insuficiente!","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnInvadirDBActionPerformed

    private void btnPhishingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhishingActionPerformed
        // TODO add your handling code here:
        if (JPrincipal.Dindin >= 100){
            JOptionPane.showMessageDialog(null,"Parabéns, você conseguiu novas ações!","Aviso",JOptionPane.INFORMATION_MESSAGE);
            JPrincipal.level = 3;
            JPrincipal.Dindin -= 2000;
            btnPhishing.setEnabled(false);
            JPrincipal.reputacao += 2500;
        }
        else{
             JOptionPane.showMessageDialog(null,"Dinheiro insuficiente!","Aviso",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnPhishingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtkWirelles;
    private javax.swing.JButton btnInvadirDB;
    private javax.swing.JButton btnPhishing;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
