/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hasckercapitalist;

import javax.swing.JOptionPane;

/**
 *
 * @author 55119
 */
public class JInternalProfissoes extends javax.swing.JInternalFrame {

    /**
     * Creates new form JInternalProfissoes
     */
    public JInternalProfissoes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEstaAnatel = new javax.swing.JButton();
        btnEstudante = new javax.swing.JButton();
        btnEstaFull = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Profissões"));
        setClosable(true);

        btnEstaAnatel.setText("Estágiario na Anatel");
        btnEstaAnatel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstaAnatelActionPerformed(evt);
            }
        });

        btnEstudante.setText("Estudante");
        btnEstudante.setEnabled(false);

        btnEstaFull.setText("Estágiario Full-Stack");
        btnEstaFull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstaFullActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstaFull, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstaAnatel, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEstudante, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEstaAnatel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEstaFull, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEstaAnatelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstaAnatelActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btnEstaAnatelActionPerformed

    private void btnEstaFullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstaFullActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstaFullActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstaAnatel;
    private javax.swing.JButton btnEstaFull;
    private javax.swing.JButton btnEstudante;
    // End of variables declaration//GEN-END:variables
}
