/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import ModelBeans.BeansUsuarios;
import ModelBeans.BeansVendedores;
import ModelDAO.DaoUsuario;
import ModelDAO.DaoVendedor;
import javax.swing.JOptionPane;
import static java.awt.Color.black;
import static java.awt.Color.gray;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author 55119
 */
public class JCadUsuario extends javax.swing.JFrame {

    

    /**
     * Creates new form JCadLogin
     */
    public JCadUsuario() {
        initComponents();
        setExtendedState(JCadUsuario.MAXIMIZED_BOTH);
        lblErroConfSenha.setVisible(false);
        lblErroNrUsu.setVisible(false);
        lblErroNrVendedor.setVisible(false);
        lblErroSenha.setVisible(false);
    }

    //variaveis importantes
    public static String nome = null;
    public static String senha = null;
    final DaoUsuario daoU = new DaoUsuario();
    final DaoVendedor daoV = new DaoVendedor();
    final BeansUsuarios modU = new BeansUsuarios();
    final BeansVendedores modV = new BeansVendedores();
    //-------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        txtConfirmarSenha = new javax.swing.JPasswordField();
        txtSenha = new javax.swing.JPasswordField();
        txtNmVendedor = new javax.swing.JFormattedTextField();
        txtADM = new javax.swing.JComboBox<>();
        txtNomeUsuario = new javax.swing.JTextField();
        txtNmUsuario = new javax.swing.JFormattedTextField();
        lblErroNrUsu = new javax.swing.JLabel();
        lblErroSenha = new javax.swing.JLabel();
        lblErroConfSenha = new javax.swing.JLabel();
        lblErroNrVendedor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTVendedor = new javax.swing.JTable();
        btnMostrarTdsVen = new javax.swing.JButton();
        btnLimparTabVend = new javax.swing.JButton();
        txtPesquisaVend = new javax.swing.JTextField();
        btnPesquisaVend = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnPagVendedores = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtUsuario = new javax.swing.JTable();
        btnMostrarTdsUser = new javax.swing.JButton();
        btnLimparTabUser = new javax.swing.JButton();
        txtPesquisaUser = new javax.swing.JTextField();
        btnPesquisaUser = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnCadastrar.setBackground(new java.awt.Color(0, 51, 153));
        btnCadastrar.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.setEnabled(false);
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 51, 153));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Cadastrar.png"))); // NOI18N
        lblTitulo.setText("Cadastro");

        txtConfirmarSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtConfirmarSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtConfirmarSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Confirmar Senha", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N
        txtConfirmarSenha.setEnabled(false);
        txtConfirmarSenha.setPreferredSize(new java.awt.Dimension(112, 25));
        txtConfirmarSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmarSenhaFocusLost(evt);
            }
        });

        txtSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Senha", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N
        txtSenha.setEnabled(false);
        txtSenha.setPreferredSize(new java.awt.Dimension(112, 25));

        txtNmVendedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Número do Vendedor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N
        txtNmVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtNmVendedor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNmVendedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNmVendedorFocusLost(evt);
            }
        });

        txtADM.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txtADM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comum", "Administrador" }));
        txtADM.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Usuário", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N

        txtNomeUsuario.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        txtNomeUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNomeUsuario.setToolTipText("");
        txtNomeUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome de Usuário", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N
        txtNomeUsuario.setEnabled(false);

        txtNmUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Número do Usuário", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N
        txtNmUsuario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtNmUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNmUsuario.setEnabled(false);

        lblErroNrUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N

        lblErroSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N

        lblErroConfSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N

        lblErroNrVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tabela de Consulta de Vendedores Cadastrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N

        jTVendedor.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jTVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Vendedor", "Nome do Vendedor", "Ativo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTVendedor.setEnabled(false);
        jTVendedor.setFocusable(false);
        jTVendedor.setRowSelectionAllowed(false);
        jTVendedor.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTVendedor);

        btnMostrarTdsVen.setBackground(new java.awt.Color(153, 204, 255));
        btnMostrarTdsVen.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        btnMostrarTdsVen.setText("Mostrar Todos");
        btnMostrarTdsVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTdsVenActionPerformed(evt);
            }
        });

        btnLimparTabVend.setBackground(new java.awt.Color(255, 255, 255));
        btnLimparTabVend.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        btnLimparTabVend.setText("Limpar");
        btnLimparTabVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTabVendActionPerformed(evt);
            }
        });

        txtPesquisaVend.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txtPesquisaVend.setForeground(new java.awt.Color(153, 153, 153));
        txtPesquisaVend.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPesquisaVend.setText("Pesquise aqui pelo nome do Vendedor...");
        txtPesquisaVend.setToolTipText("");
        txtPesquisaVend.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaVendFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisaVendFocusLost(evt);
            }
        });

        btnPesquisaVend.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisaVend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btnPesquisaVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaVendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnMostrarTdsVen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(251, 251, 251)
                            .addComponent(btnLimparTabVend, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(txtPesquisaVend, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPesquisaVend)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesquisaVend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPesquisaVend, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarTdsVen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparTabVend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnLogin.setText("Ir ao Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnPagVendedores.setBackground(new java.awt.Color(0, 51, 153));
        btnPagVendedores.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        btnPagVendedores.setForeground(new java.awt.Color(255, 255, 255));
        btnPagVendedores.setText("Ir para a página Vendedores");
        btnPagVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagVendedoresActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tabela de Consulta de Usuários Cadastrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N

        jtUsuario.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jtUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Usuário", "Nome do Vendedor", "É adm?", "Código do Vendedor", "Senha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtUsuario.getTableHeader().setReorderingAllowed(false);
        jtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtUsuarioMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jtUsuario);

        btnMostrarTdsUser.setBackground(new java.awt.Color(153, 204, 255));
        btnMostrarTdsUser.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        btnMostrarTdsUser.setText("Mostrar Todos");
        btnMostrarTdsUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTdsUserActionPerformed(evt);
            }
        });

        btnLimparTabUser.setBackground(new java.awt.Color(255, 255, 255));
        btnLimparTabUser.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        btnLimparTabUser.setText("Limpar");
        btnLimparTabUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTabUserActionPerformed(evt);
            }
        });

        txtPesquisaUser.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txtPesquisaUser.setForeground(new java.awt.Color(153, 153, 153));
        txtPesquisaUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPesquisaUser.setText("Pesquise aqui pelo nome do Usuario...");
        txtPesquisaUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisaUserFocusLost(evt);
            }
        });

        btnPesquisaUser.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisaUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btnPesquisaUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnMostrarTdsUser, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257)
                        .addComponent(btnLimparTabUser, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane4)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(txtPesquisaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPesquisaUser))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPesquisaUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPesquisaUser, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarTdsUser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparTabUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btnAlterar.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Nirmala UI", 1, 14)); // NOI18N
        jButton1.setText("Limpar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPagVendedores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtADM, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNmUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblErroNrUsu)))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNmVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblErroNrVendedor))
                            .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(lblErroSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(lblErroConfSenha)))
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPagVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNmUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErroNrUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErroNrVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtADM, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNmVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErroSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblErroConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        txtNmVendedor.getAccessibleContext().setAccessibleName("Código do Vendedor");
        txtNmUsuario.getAccessibleContext().setAccessibleName("Código do Usuário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Botões--------------------
    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        //Variaveis
        String nomeusu = txtNomeUsuario.getText().trim();
        String senha1 = txtSenha.getText();
        String senha2 = txtConfirmarSenha.getText();
        int adm;
        //-------------
        //if para definir se é adm
        if(txtADM.getSelectedItem() == "Comum"){
            adm = 0;
        }
        else{
            adm = 1;
        }
        //verifica se esta vazio
        if (nomeusu.isEmpty() || senha1.isEmpty() || senha2.isEmpty() || txtNmVendedor.getText().isEmpty() || txtNmUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos!");
        } else 
        {
            //Variaveis, essas precisam estar depois da verificação de vazio
            int codVen = Integer.valueOf(txtNmVendedor.getText());
            int codUser = Integer.parseInt(txtNmUsuario.getText());
            //------------
            //verifica se as senhas são compativeis
            if (senha1.equals(senha2)) 
            {
                if(txtNmUsuario.getText().equals( txtNmVendedor.getText())){
                    try {
                        //seta os valores no beans
                        modU.set_codUser(codUser);
                        modU.set_nome(nomeusu);
                        modU.set_adm(adm);
                        modU.set_codVen(codVen);
                        modU.set_senha(senha2);
                        //inicia o cadastro e guarda o resultado
                        int r = daoU.cadastrar(modU);
                        //verifica o resultado
                        if(r == 1){
                            //se deu certo ele carrega a config inicial e atualiza a tabela usuarios
                            tInicial();
                            daoU.mostrarTodos((DefaultTableModel) jtUsuario.getModel());
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());//mostra o erro
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Codigo do usuario tem que ser o mesmo do vendedor!");
                }
            } else 
            {
                JOptionPane.showMessageDialog(null, "As senhas estão diferentes, tente novamente!");
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        //Variaveis
        String nomeusu = txtNomeUsuario.getText().trim();
        String senha1 = txtSenha.getText();
        String senha2 = txtConfirmarSenha.getText();
        int adm;
        //-------------
        //if para definir se é adm
        if(txtADM.getSelectedItem() == "Comum"){
            adm = 0;
        }
        else{
            adm = 1;
        }
        //verifica se esta vazio
        if (nomeusu.isEmpty() || senha1.isEmpty() || senha2.isEmpty() || txtNmVendedor.getText().isEmpty() || txtNmUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos!");
        } else 
        {
            //Variaveis, essas precisam estar depois da verificação de vazio
            int codVen = Integer.valueOf(txtNmVendedor.getText());
            int codUser = Integer.parseInt(txtNmUsuario.getText());
            //------------
            //verifica se as senhas são compativeis
            if (senha1.equals(senha2)) 
            {
                if(txtNmUsuario.getText().equals( txtNmVendedor.getText())){
                    try {
                        //seta os valores no beans
                        modU.set_codUser(codUser);
                        modU.set_nome(nomeusu);
                        modU.set_adm(adm);
                        modU.set_codVen(codVen);
                        modU.set_senha(senha2);
                        //inicia o cadastro e guarda o resultado
                        int r = daoU.alterar(modU);
                        //verifica o resultado
                        if(r == 1){
                            //se deu certo ele carrega a config inicial e atualiza a tabela usuarios
                            tInicial();
                            daoU.mostrarTodos((DefaultTableModel) jtUsuario.getModel());
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());//mostra o erro
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "Codigo do usuario tem que ser o mesmo do vendedor!");
                }
            } else 
            {
                JOptionPane.showMessageDialog(null, "As senhas estão diferentes, tente novamente!");
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        //Verifica se esta vazio
        if (txtNmUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor preencha o campo codigo do Usuario!");
            txtNmUsuario.requestFocus();
        } else {
            //variaveis
            int cod = Integer.valueOf(txtNmUsuario.getText());
            //---------
            //try catch para excluir
            try {
                //seta os dados e executa a exclusão
                modU.set_codUser(cod);
                int r = daoU.excluir(modU);
                //verifica se deu certo
                if (r == 1) {
                    //se deu certo, atualiza a tabela clientes e carrega a config inicial
                    tInicial();
                    daoU.mostrarTodos((DefaultTableModel) jtUsuario.getModel());
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro: " + e);//exibe o erro
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        if(txtNmVendedor.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o codigo do vendedor!");
            txtNmVendedor.requestFocus();
        }else{
            int codVen = Integer.parseInt(txtNmVendedor.getText());
            try {
                //seta valores no Beans
                modU.set_codVen(codVen);
                //excuta a consulta
                daoU.consulta(modU);
                //verifica se retornou algo
                if (daoU.rs.first()) {
                    //se existir ele exibe a mensagem 
                    JOptionPane.showMessageDialog(null, "Usuario ja está cadastrado!");
                    tInicial();
                } else {
                    //se não existir ele libera o cadastro
                    JOptionPane.showMessageDialog(null, "Usuário não encontrado, pode cadastra-lo");
                    liberar();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Problemas de conexão com a base de dados: " + e.getMessage());//exibe o erro
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnMostrarTdsVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTdsVenActionPerformed
        // TODO add your handling code here:
        //carrega os dados do  vendedor
        daoV.mostrarTodosL((DefaultTableModel) jTVendedor.getModel());
    }//GEN-LAST:event_btnMostrarTdsVenActionPerformed

    private void btnLimparTabVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTabVendActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabela = (DefaultTableModel) jTVendedor.getModel();
        tabela.setNumRows(0);
        txtPesquisaVend.setText("Pesquise aqui pelo nome do Vendedor...");
        txtPesquisaVend.setForeground(gray);
    }//GEN-LAST:event_btnLimparTabVendActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        new JLogin().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnPagVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagVendedoresActionPerformed
        // TODO add your handling code here:
        new JVendedores().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPagVendedoresActionPerformed

    private void btnMostrarTdsUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTdsUserActionPerformed
        // TODO add your handling code here:
        daoU.mostrarTodos((DefaultTableModel) jtUsuario.getModel());
    }//GEN-LAST:event_btnMostrarTdsUserActionPerformed

    private void btnLimparTabUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTabUserActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tabela = (DefaultTableModel) jtUsuario.getModel();
        tabela.setNumRows(0);
        txtPesquisaUser.setText("Pesquise aqui pelo nome do Usuario...");
        txtPesquisaUser.setForeground(gray);
    }//GEN-LAST:event_btnLimparTabUserActionPerformed

    //----------------------

    //Funções------------------

    private void pegarValor(){
        txtNmUsuario.setText((String) jtUsuario.getValueAt(jtUsuario.getSelectedRow(), 0));
        txtNomeUsuario.setText((String) jtUsuario.getValueAt(jtUsuario.getSelectedRow(), 1));
        txtNmVendedor.setText((String) jtUsuario.getValueAt(jtUsuario.getSelectedRow(), 3));
        txtSenha.setText((String) jtUsuario.getValueAt(jtUsuario.getSelectedRow(), 4));
        txtConfirmarSenha.setText((String) jtUsuario.getValueAt(jtUsuario.getSelectedRow(), 4));
        
        String adm =  (String) jtUsuario.getValueAt(jtUsuario.getSelectedRow(), 2);
        if("1".equals(adm)){
            txtADM.setSelectedItem("Administrador");
        }
        else{
            txtADM.setSelectedItem("Comum");
        }
    }

    private void confAlterar(){
        txtNmUsuario.setEnabled(false);
        txtSenha.setEnabled(true);
        txtNomeUsuario.setEnabled(true);
        txtConfirmarSenha.setEnabled(true);
        txtNmVendedor.setEnabled(false);
        
        btnCadastrar.setEnabled(false);
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnConsultar.setEnabled(false);
    }
    
    public void tInicial(){
        limpar();
        txtNmUsuario.setEnabled(false);
        txtSenha.setEnabled(false);
        txtNomeUsuario.setEnabled(false);
        txtConfirmarSenha.setEnabled(false);
        txtNmVendedor.setEnabled(true);
        
        btnCadastrar.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnConsultar.setEnabled(true);
    }
    
    private void limpar(){
        txtNmUsuario.setText("");
        txtSenha.setText("");
        txtNomeUsuario.setText("");
        txtConfirmarSenha.setText("");
        txtNmVendedor.setText("");
    }

    private void liberar() {
        txtNmUsuario.setEnabled(false);
        txtSenha.setEnabled(true);
        txtNomeUsuario.setEnabled(true);
        txtConfirmarSenha.setEnabled(true);
        txtNmVendedor.setEnabled(false);
        
        btnCadastrar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnConsultar.setEnabled(false);
        
        txtNmUsuario.setText(txtNmVendedor.getText());
    }
    //----------------------

    private void txtConfirmarSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmarSenhaFocusLost
        // TODO add your handling code here:
        if(txtNomeUsuario.isEnabled()){
            if(txtConfirmarSenha.getText().equals("")){

            }
            else{
                if(txtConfirmarSenha.getText().equals(txtSenha.getText())){
                    lblErroConfSenha.setVisible(false);
                    lblErroSenha.setVisible(false);
                }
                else{
                    lblErroConfSenha.setVisible(true);
                    lblErroSenha.setVisible(true);
                    JOptionPane.showMessageDialog(null, "As senhas não coincidem!");
                }
            }
        }
    }//GEN-LAST:event_txtConfirmarSenhaFocusLost

    private void txtNmVendedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNmVendedorFocusLost
        // TODO add your handling code here:
        if(txtNomeUsuario.isEnabled()){  
            if(txtNmVendedor.getText().equals("")){

            }
            else{
                if(txtNmVendedor.getText().equals(txtNmUsuario.getText())){
                    lblErroNrUsu.setVisible(false);
                    lblErroNrVendedor.setVisible(false);
                }
                else{
                    lblErroNrUsu.setVisible(true);
                    lblErroNrVendedor.setVisible(true);
                    JOptionPane.showMessageDialog(null, "O número do usuário deve ser o número do vendedor!");
                }
            }
        }
    }//GEN-LAST:event_txtNmVendedorFocusLost

    private void txtPesquisaVendFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaVendFocusGained
        // TODO add your handling code here:
        if(txtPesquisaVend.getText().equals("Pesquise aqui pelo nome do Vendedor...")){
            txtPesquisaVend.setText("");
            txtPesquisaVend.setForeground(black);
        }
        else{
            txtPesquisaVend.setForeground(black);
        }
    }//GEN-LAST:event_txtPesquisaVendFocusGained

    private void txtPesquisaVendFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaVendFocusLost
        // TODO add your handling code here:
        if(txtPesquisaVend.getText().equals("")){
            txtPesquisaVend.setText("Pesquise aqui pelo nome do Vendedor...");
            txtPesquisaVend.setForeground(gray);
        }
        else{
            txtPesquisaVend.setForeground(black);
        }
    }//GEN-LAST:event_txtPesquisaVendFocusLost

    private void txtPesquisaUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaUserFocusGained
        // TODO add your handling code here:
        if(txtPesquisaUser.getText().equals("Pesquise aqui pelo nome do Usuario...")){
            txtPesquisaUser.setText("");
            txtPesquisaUser.setForeground(black);
        }
        else{
            txtPesquisaUser.setForeground(black);
        }
    }//GEN-LAST:event_txtPesquisaUserFocusGained

    private void txtPesquisaUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaUserFocusLost
        // TODO add your handling code here:
         if(txtPesquisaUser.getText().equals("")){
            txtPesquisaUser.setText("Pesquise aqui pelo nome do Usuario...");
            txtPesquisaUser.setForeground(gray);
        }
        else{
            txtPesquisaUser.setForeground(black);
        }
    }//GEN-LAST:event_txtPesquisaUserFocusLost

    private void jtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsuarioMouseClicked
        // TODO add your handling code here:
        if (jtUsuario.getSelectedRow() != -1) {
            String[] options ={"Alterar/Excluir", "Cancelar" };//define as opções
                    //faz a pergunta 
                    int x = JOptionPane.showOptionDialog(null, "Usuario selecionado, você deseja:", "Escolha uma das opções", 
                            JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
                    //confere a resposta
                    switch(x){
                        case 0: //caso escolha alterar/excluir ele carrega a configuração de alteração
                                confAlterar();
                                pegarValor();
                            break;
                        case 1: //caso escolha cancelar, ele carrega a configuração da tela inicial
                                tInicial();
                            break;
                        default: ;
                    }
        }
    }//GEN-LAST:event_jtUsuarioMouseClicked

    private void btnPesquisaVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaVendActionPerformed
        // TODO add your handling code here:
        if(txtPesquisaVend.getText().isEmpty() || "Pesquise aqui pelo nome do Vendedor...".equals(txtPesquisaVend.getText())){
            JOptionPane.showMessageDialog(null, "Preencha o campo de pesquisa!");//exibe o erro
        }else{
            modV.setNome(txtPesquisaVend.getText());
            daoV.mostrarPorNomeL(modV, (DefaultTableModel) jTVendedor.getModel());
        }
    }//GEN-LAST:event_btnPesquisaVendActionPerformed

    private void btnPesquisaUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaUserActionPerformed
        // TODO add your handling code here:
        if(txtPesquisaUser.getText().isEmpty() || "Pesquise aqui pelo nome do Usuario...".equals(txtPesquisaUser.getText()) ){
            JOptionPane.showMessageDialog(null, "Preencha o campo de pesquisa!");//exibe o erro
        }else{
            modU.set_nome(txtPesquisaUser.getText());
            daoU.mostrarPorNome(modU, (DefaultTableModel) jtUsuario.getModel());
        }
    }//GEN-LAST:event_btnPesquisaUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        txtConfirmarSenha.setText("");
        txtNmUsuario.setText("");
        txtNmVendedor.setText("");
        txtNomeUsuario.setText("");
        txtSenha.setText("");
        txtADM.setSelectedItem("Comum");
    }//GEN-LAST:event_jButton1ActionPerformed
    //-------------------
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCadUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCadUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimparTabUser;
    private javax.swing.JButton btnLimparTabVend;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMostrarTdsUser;
    private javax.swing.JButton btnMostrarTdsVen;
    private javax.swing.JButton btnPagVendedores;
    private javax.swing.JButton btnPesquisaUser;
    private javax.swing.JButton btnPesquisaVend;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTVendedor;
    private javax.swing.JTable jtUsuario;
    private javax.swing.JLabel lblErroConfSenha;
    private javax.swing.JLabel lblErroNrUsu;
    private javax.swing.JLabel lblErroNrVendedor;
    private javax.swing.JLabel lblErroSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JComboBox<String> txtADM;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JFormattedTextField txtNmUsuario;
    private javax.swing.JFormattedTextField txtNmVendedor;
    private javax.swing.JTextField txtNomeUsuario;
    private javax.swing.JTextField txtPesquisaUser;
    private javax.swing.JTextField txtPesquisaVend;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables

    
}
