/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import ModelBeans.BeansVendedores;
import ModelDAO.DaoVendedor;
import static java.awt.Color.black;
import static java.awt.Color.gray;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pamel
 */
public class JCadVendedor extends javax.swing.JFrame {

    /**
     * Creates new form JCadVendedor
     */
    public JCadVendedor() {
        initComponents();
        txtCodVend.setVisible(false);
        lblCodVen.setVisible(false);
        txtAtivo.setVisible(false);
        lblAtivo.setVisible(false);
        setExtendedState(JCadVendedor.MAXIMIZED_BOTH);
    }

    //variaveis importantes
    final BeansVendedores mod = new BeansVendedores();
    final DaoVendedor dao = new DaoVendedor();
    //----------------------

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblCodVen = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtComissao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSalFix = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnAtivo = new javax.swing.JButton();
        txtCodVend = new javax.swing.JTextField();
        txtAtivo = new javax.swing.JTextField();
        lblAtivo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtVendedor = new javax.swing.JTable();
        btnMostrarTds = new javax.swing.JButton();
        btnLimparTabela = new javax.swing.JButton();
        txtPesquisaVend = new javax.swing.JTextField();
        btnPesquisaVend = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnPagVendedores = new javax.swing.JButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Cadastro e Consulta de Vendedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N

        lblCodVen.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        lblCodVen.setText("Código do Vendedor");

        txtNome.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        txtNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel3.setText("Salário Fixo");

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel5.setText("Comissão");

        txtComissao.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        txtComissao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtComissao.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jLabel9.setText("Nome do Vendedor");

        txtSalFix.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        txtSalFix.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSalFix.setEnabled(false);

        btnLimpar.setBackground(new java.awt.Color(255, 255, 255));
        btnLimpar.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAdd.setBackground(new java.awt.Color(153, 255, 102));
        btnAdd.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        btnAdd.setText("Adicionar");
        btnAdd.setEnabled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnConsultar.setBackground(new java.awt.Color(153, 153, 255));
        btnConsultar.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnAlterar.setBackground(new java.awt.Color(255, 153, 102));
        btnAlterar.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnAtivo.setBackground(new java.awt.Color(255, 102, 102));
        btnAtivo.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        btnAtivo.setText("Desabilitar");
        btnAtivo.setEnabled(false);
        btnAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        txtCodVend.setEditable(false);
        txtCodVend.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        txtCodVend.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCodVend.setEnabled(false);

        txtAtivo.setEditable(false);
        txtAtivo.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        txtAtivo.setEnabled(false);

        lblAtivo.setFont(lblCodVen.getFont());
        lblAtivo.setText("Ativo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCodVen)
                            .addComponent(jLabel9))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodVend, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtSalFix, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 39, Short.MAX_VALUE)
                                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtAtivo))
                                .addGap(26, 26, 26))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAtivo)
                                .addGap(87, 87, 87)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtCodVend, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodVen)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAtivo)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSalFix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tabela de Consulta de Vendedores Cadastrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nirmala UI", 1, 14))); // NOI18N

        jtVendedor.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jtVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Vendedor", "Nome do Vendedor", "Salário Fixo", "Comissão %", "Ativo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtVendedor.getTableHeader().setReorderingAllowed(false);
        jtVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtVendedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtVendedor);

        btnMostrarTds.setBackground(new java.awt.Color(153, 204, 255));
        btnMostrarTds.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        btnMostrarTds.setText("Mostrar Todos");
        btnMostrarTds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTdsActionPerformed(evt);
            }
        });

        btnLimparTabela.setBackground(new java.awt.Color(255, 255, 255));
        btnLimparTabela.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        btnLimparTabela.setText("Limpar");
        btnLimparTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTabelaActionPerformed(evt);
            }
        });

        txtPesquisaVend.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        txtPesquisaVend.setForeground(new java.awt.Color(153, 153, 153));
        txtPesquisaVend.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPesquisaVend.setText("Pesquise aqui pelo nome do vendedor...");
        txtPesquisaVend.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPesquisaVendFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPesquisaVendFocusLost(evt);
            }
        });

        btnPesquisaVend.setBackground(new java.awt.Color(255, 255, 255));
        btnPesquisaVend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lupa.png"))); // NOI18N
        btnPesquisaVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaVendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnMostrarTds, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimparTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(txtPesquisaVend, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisaVend)
                .addContainerGap(434, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisaVend)
                    .addComponent(btnPesquisaVend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLimparTabela, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnMostrarTds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ico_vend.png"))); // NOI18N
        jLabel2.setText("Cadastro, Alteração e Exclusão de Vendedores");

        btnPagVendedores.setBackground(new java.awt.Color(0, 51, 153));
        btnPagVendedores.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        btnPagVendedores.setForeground(new java.awt.Color(255, 255, 255));
        btnPagVendedores.setText("Ir para a página Vendedores");
        btnPagVendedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagVendedoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPagVendedores))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPagVendedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jMenu4.setText("Cadastros e Consultas");
        jMenu4.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem9.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jMenuItem9.setText("Clientes");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem1.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jMenuItem1.setText("Pedidos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem4.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jMenuItem4.setText("Produtos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem10.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jMenuItem10.setText("Relatórios");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem2.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jMenuItem2.setText("Vendedores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar3.add(jMenu4);

        jMenu2.setText("Outras Opções");
        jMenu2.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N

        jMenuItem5.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jMenuItem5.setText("Menu Principal");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jMenuItem6.setText("Ajuda");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jMenuItem7.setText("Sair");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar3.add(jMenu2);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Botões----
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        //Variaveis
        String nome = txtNome.getText().trim();
        //--------
        //if para ver se esta vazio
        if (txtSalFix.getText().isEmpty() || nome.isEmpty() || txtComissao.getText().isEmpty()) {
            //se estiver ele exibe a mensagem
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos!");
        } else {
            //Variaveis
            //conversão só é feita se o textBox não estiver vazio
            double salFixo = Double.parseDouble(txtSalFix.getText().trim());
            double comissao = Double.parseDouble(txtComissao.getText().trim());
            //--------
            try {
                //seta os valores no Beans
                mod.setNome(nome);
                mod.setSalFixo(salFixo);
                mod.setComissao(comissao);
                mod.setAtivo(1);
                //executa o cadastro e guarda o retorno
                int r = dao.cadastrar(mod);
                //verifica se cadastrou com sucesso
                if (r == 1) {
                    //se deu certo, atualiza a tabela clientes e carrega a config inicial
                    tInicial();
                    dao.mostrarTodos((DefaultTableModel) jtVendedor.getModel());
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro: " + e);//exibe o erro
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        //Variaveis
        String nome = txtNome.getText().trim();
        //---------
        //Verifica se esta vazio
        if (nome.isEmpty() || txtSalFix.getText().isEmpty() || txtComissao.getText().isEmpty()) {
            //se estiver ele exibe a mensagem
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos!");
        } else {
            //Variaveis
            //conversão só é feita se o textBox não estiver vazio
            double comissao = Double.parseDouble(txtComissao.getText().trim());
            double salFixo = Double.parseDouble(txtSalFix.getText().trim());
            int cod = Integer.parseInt(txtCodVend.getText().trim());
            //------
            try {
                //seta os valores no Beans
                mod.setCodVend(cod);
                mod.setNome(nome);
                mod.setComissao(comissao);
                mod.setSalFixo(salFixo);
                //executa a alteraão e guarda o resultado
                int r = dao.alterar(mod);
                //verifica se deu certo
                if (r == 1) {
                    //se deu certo, atualiza a tabela clientes e carrega a config inicial
                    tInicial();
                    dao.mostrarTodos((DefaultTableModel) jtVendedor.getModel());
                }
            } catch (Exception e) {
                //exibe o erro
                JOptionPane.showMessageDialog(null, "Erro: " + e);
            }
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtivoActionPerformed
        // TODO add your handling code here:
        //verifica se esta vazio
        if (txtCodVend.getText().isEmpty()) {
            //se estiver ele exibe a mensagem
            JOptionPane.showMessageDialog(null, "Por favor preencha o campo Código do vendedor!");
        } else {
            //Variaveis
            //conversão só é feita se o textBox não estiver vazio
            int cod = Integer.valueOf(txtCodVend.getText().trim());
            //--------
            //verifica se a operação é para ativar ou desativar o vendedor
            if ("Desabilitar".equals(btnAtivo.getText())) {
                try {
                    //seta os valores no Beans
                    mod.setCodVend(cod);
                    mod.setAtivo(0);//se for desabilitar ele seta como 0
                    //executa e guarda o retorno
                    int r = dao.mudarAtivo(mod);
                    //verifica se deu certo
                    if (r == 1) {
                        //se deu certo, atualiza a tabela clientes e carrega a config inicial
                        tInicial();
                        dao.mostrarTodos((DefaultTableModel) jtVendedor.getModel());
                    }
                } catch (Exception e) {
                    //exibe o erro
                    JOptionPane.showMessageDialog(null, "Erro: " + e);
                }
            } else {
                try {
                    //seta os valores no Beans
                    mod.setCodVend(cod);
                    mod.setAtivo(1);//se for habilitar ele seta como 1
                    //executa e guarda o retorno
                    int r = dao.mudarAtivo(mod);
                    //verifica se deu certo
                    if (r == 1) {
                        //se deu certo, atualiza a tabela clientes e carrega a config inicial
                        tInicial();
                        dao.mostrarTodos((DefaultTableModel) jtVendedor.getModel());
                    }
                } catch (Exception e) {
                    //exibe o erro
                    JOptionPane.showMessageDialog(null, "Erro: " + e);
                }
            }

        }
    }//GEN-LAST:event_btnAtivoActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        //Variaveis
        String nome = txtNome.getText().trim();
        //-----------
        //Verifica se esta vazio
        if (nome.isEmpty()) {
            //se estiver ele exibe a mensagem
            JOptionPane.showMessageDialog(null, "Por favor preencha o campo do nome!");
        } else {
            try {
                //seta os valores no Beans
                mod.setNome(nome);
                //executa a pesquisa
                dao.consulta(mod);
                //verifica se tem registro
                if (dao.rs.first()) {
                    //se tiver registro ele bloqueia o cadastro
                    JOptionPane.showMessageDialog(null, "Vendedor já cadastrado!");
                } else {
                    //se não tiver ele libera o cadastro
                    JOptionPane.showMessageDialog(null, "Vendedor não encontrado, pode cadastra-lo");
                    liberar();
                }
            } catch (SQLException e) {
                //exibe o erro
                JOptionPane.showMessageDialog(null, "Problemas de conexão com a base de dados: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnMostrarTdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTdsActionPerformed
        // TODO add your handling code here:
        //carrega os dados para a tabela
        dao.mostrarTodos((DefaultTableModel) jtVendedor.getModel());
    }//GEN-LAST:event_btnMostrarTdsActionPerformed

    private void btnLimparTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTabelaActionPerformed
        // TODO add your handling code here:
        //instancia a tabela
        DefaultTableModel tabela = (DefaultTableModel) jtVendedor.getModel();
        tabela.setNumRows(0);//zera as linhas
        txtPesquisaVend.setText("Pesquise aqui pelo nome do vendedor...");
        txtPesquisaVend.setForeground(gray);
    }//GEN-LAST:event_btnLimparTabelaActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // TODO add your handling code here:
        //carrega a configuração inicial
        tInicial();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void jtVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtVendedorMouseClicked
        // TODO add your handling code here:
        if (jtVendedor.getSelectedRow() != -1) {

            //pega os valores selecionados e carrega a config de alteração
            pegarValor();
            confAlterar();
        }
    }//GEN-LAST:event_jtVendedorMouseClicked

    private void btnPesquisaVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaVendActionPerformed
        // TODO add your handling code here:
        mod.setNome(txtPesquisaVend.getText());
        dao.mostrarPorNome(mod, (DefaultTableModel) jtVendedor.getModel());
    }//GEN-LAST:event_btnPesquisaVendActionPerformed

    //-------------
    //Menu------------
    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        new JCliente().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        new JPedido().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new JProdutos().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        new JRelatorios().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new JVendedores().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new JMenu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        new JAjuda().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    //-----------------
    //Funções----------------
    public void tInicial() {
        limpar();
        txtCodVend.setEnabled(false);
        txtComissao.setEnabled(false);
        txtNome.setEnabled(true);
        txtSalFix.setEnabled(false);
        txtCodVend.setVisible(false);
        lblCodVen.setVisible(false);

        btnAdd.setEnabled(false);
        btnConsultar.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnAtivo.setEnabled(false);
    }

    public void confAlterar() {
        txtCodVend.setEnabled(false);
        txtComissao.setEnabled(true);
        txtNome.setEnabled(true);
        txtSalFix.setEnabled(true);
        txtCodVend.setVisible(true);
        lblCodVen.setVisible(true);
        txtAtivo.setVisible(true);
        lblAtivo.setVisible(true);

        btnAdd.setEnabled(false);
        btnConsultar.setEnabled(false);
        btnAlterar.setEnabled(true);
        btnAtivo.setEnabled(true);
    }

    public void pegarValor() {
        txtCodVend.setText((String) jtVendedor.getValueAt(jtVendedor.getSelectedRow(), 0));
        txtNome.setText((String) jtVendedor.getValueAt(jtVendedor.getSelectedRow(), 1));
        txtSalFix.setText((String) jtVendedor.getValueAt(jtVendedor.getSelectedRow(), 2));
        txtComissao.setText((String) jtVendedor.getValueAt(jtVendedor.getSelectedRow(), 3));

        String t = (String) jtVendedor.getValueAt(jtVendedor.getSelectedRow(), 4);
        if ("1".equals(t)) {
            btnAtivo.setText("Desabilitar");
            txtAtivo.setText("Ativo");
        } else {
            btnAtivo.setText("Habilitar");
            txtAtivo.setText("Desativado");
        }

    }

    public void liberar() {
        txtComissao.setEnabled(true);
        txtSalFix.setEnabled(true);
        txtNome.setEnabled(false);

        btnAdd.setEnabled(true);
        btnConsultar.setEnabled(false);
    }

    public void limpar() {
        txtCodVend.setText("");
        txtComissao.setText("");
        txtNome.setText("");
        txtSalFix.setText("");
        txtAtivo.setText("");
    }

    //---------------------
    private void txtPesquisaVendFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaVendFocusGained
        // TODO add your handling code here:
        if (txtPesquisaVend.getText().equals("Pesquise aqui pelo nome do vendedor...")) {
            txtPesquisaVend.setText("");
            txtPesquisaVend.setForeground(black);
        } else {
            txtPesquisaVend.setForeground(black);
        }
    }//GEN-LAST:event_txtPesquisaVendFocusGained

    private void txtPesquisaVendFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPesquisaVendFocusLost
        // TODO add your handling code here:
        if (txtPesquisaVend.getText().equals("")) {
            txtPesquisaVend.setText("Pesquise aqui pelo nome do vendedor...");
            txtPesquisaVend.setForeground(gray);
        } else {
            txtPesquisaVend.setForeground(black);
        }
    }//GEN-LAST:event_txtPesquisaVendFocusLost

    private void btnPagVendedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagVendedoresActionPerformed
        // TODO add your handling code here:
        
        new JVendedores().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPagVendedoresActionPerformed
    //------------------

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JCadVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JCadVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JCadVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JCadVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JCadVendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAtivo;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnLimparTabela;
    private javax.swing.JButton btnMostrarTds;
    private javax.swing.JButton btnPagVendedores;
    private javax.swing.JButton btnPesquisaVend;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtVendedor;
    private javax.swing.JLabel lblAtivo;
    private javax.swing.JLabel lblCodVen;
    private javax.swing.JTextField txtAtivo;
    private javax.swing.JTextField txtCodVend;
    private javax.swing.JTextField txtComissao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisaVend;
    private javax.swing.JTextField txtSalFix;
    // End of variables declaration//GEN-END:variables
}
